version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins-ci
    privileged: true
    user: root
    ports:
      - "8090:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins-data:/var/jenkins_data
      - ./jenkins-config/jenkins.yaml:/var/jenkins_home/casc.yaml
      - ../:/workspace
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
    networks:
      - jenkins-network
      - buy-01_default  # Connect to main app network

  jenkins-agent:
    image: jenkins/inbound-agent:latest-jdk21
    container_name: jenkins-agent
    privileged: true
    user: root
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_AGENT_NAME=docker-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - jenkins_agent_home:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-network
    depends_on:
      - jenkins

networks:
  jenkins-network:
    driver: bridge
  buy-01_default:
    external: true

volumes:
  jenkins_home:
  jenkins_agent_home:
